-- EXERCICIO DA OFICINA

CREATE TABLE CARRO(

	IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
	ID_MARCA INT,
	PLACA VARCHAR(15) NOT NULL,
	MODELO VARCHAR(20) NOT NULL
	
);

CREATE TABLE TELEFONE(

	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	ID_CLIENTE INT,
	TIPO ENUM('RES', 'CEL', 'COM') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL	

);

CREATE TABLE CLIENTE(

	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	ID_CARRO INT UNIQUE,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M', 'F') NOT NULL
		
);

CREATE TABLE COR(

	IDCOR INT PRIMARY KEY AUTO_INCREMENT,
	COR VARCHAR(30) UNIQUE

);

CREATE TABLE MARCA(

	IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
	MARCA VARCHAR(20) NOT NULL

);

CREATE TABLE CARRO_COR(

	ID_CARRO INT,
	ID_COR INT,
	PRIMARY KEY(ID_CARRO, ID_COR)
	
);


/* CONSTRAINTS */

ALTER TABLE TELEFONE 
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE);


ALTER TABLE CLIENTE
ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY(ID_CARRO)
REFERENCES CARRO(IDCARRO);


ALTER TABLE CARRO
ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY(ID_MARCA)
REFERENCES MARCA(IDMARCA);


ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_COR
FOREIGN KEY(ID_COR)
REFERENCES COR(IDCOR);


ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_CARRO
FOREIGN KEY(ID_CARRO)
REFERENCES CARRO(IDCARRO);

/* PREENCHER O BANCO COM NO MINIMO 10 CLIENTES */

INSERT INTO CARRO VALUES(NULL, NULL, 'HAH9989', 'Uno');
INSERT INTO CARRO VALUES(NULL, NULL, 'HAH9980', 'Fiesta');
INSERT INTO CARRO VALUES(NULL, NULL, 'HAH9981', 'i320');
INSERT INTO CARRO VALUES(NULL, NULL, 'HAH9982', 'Civic');
INSERT INTO CARRO VALUES(NULL, NULL, 'HAH9983', 'Gol');
INSERT INTO CARRO VALUES(NULL, NULL, 'HAH9984', 'Lancer');
INSERT INTO CARRO VALUES(NULL, NULL, 'HAH9985', 'Supra');
INSERT INTO CARRO VALUES(NULL, NULL, 'HAH9986', 'RX7');
INSERT INTO CARRO VALUES(NULL, NULL, 'HAH9987', 'RX5');
INSERT INTO CARRO VALUES(NULL, NULL, 'HAH9988', 'Skyline');

INSERT INTO CLIENTE VALUES(NULL, 1, 'JOSÉ', 'M');
INSERT INTO CLIENTE VALUES(NULL, 2, 'MARIA', 'F');
INSERT INTO CLIENTE VALUES(NULL, 3, 'LUA', 'F');
INSERT INTO CLIENTE VALUES(NULL, 4, 'CLAUDETE', 'F');
INSERT INTO CLIENTE VALUES(NULL, 5, 'ELLEN', 'F');
INSERT INTO CLIENTE VALUES(NULL, 6, 'RICHARD', 'M');
INSERT INTO CLIENTE VALUES(NULL, 7, 'RICK', 'M');
INSERT INTO CLIENTE VALUES(NULL, 8, 'MALMSTEEN', 'M');
INSERT INTO CLIENTE VALUES(NULL, 9, 'JOELMA', 'F');
INSERT INTO CLIENTE VALUES(NULL, 10, 'CHIMBINHA', 'M');

INSERT INTO MARCA VALUES(NULL, 'FORD'); 
INSERT INTO MARCA VALUES(NULL, 'FIAT');
INSERT INTO MARCA VALUES(NULL, 'VOLKSWAGEN');
INSERT INTO MARCA VALUES(NULL, 'MAZDA');
INSERT INTO MARCA VALUES(NULL, 'NISSAN');
INSERT INTO MARCA VALUES(NULL, 'HONDA');
INSERT INTO MARCA VALUES(NULL, 'MITSUBISHI'); 
INSERT INTO MARCA VALUES(NULL, 'BMW');
INSERT INTO MARCA VALUES(NULL, 'TOYOTA');
INSERT INTO MARCA VALUES(NULL, 'FERRARI');

INSERT INTO TELEFONE VALUES(NULL, 10, 'RES', '33333333');
INSERT INTO TELEFONE VALUES(NULL, 9, 'COM', '999999999');
INSERT INTO TELEFONE VALUES(NULL, 8, 'CEL', '944444444');
INSERT INTO TELEFONE VALUES(NULL, 7, 'CEL', '988888888');
INSERT INTO TELEFONE VALUES(NULL, 6, 'CEL', '977777777');
INSERT INTO TELEFONE VALUES(NULL, 5, 'COM', '966666666');
INSERT INTO TELEFONE VALUES(NULL, 4, 'COM', '955555555');
INSERT INTO TELEFONE VALUES(NULL, 3, 'RES', '22222222');
INSERT INTO TELEFONE VALUES(NULL, 2, 'RES', '11111111');
INSERT INTO TELEFONE VALUES(NULL, 1, 'RES', '44444444');


INSERT INTO COR VALUES(NULL, 'PRETO');
INSERT INTO COR VALUES(NULL, 'VERMELHO');
INSERT INTO COR VALUES(NULL, 'BRANCO');
INSERT INTO COR VALUES(NULL, 'PRATA');
INSERT INTO COR VALUES(NULL, 'AZUL');
INSERT INTO COR VALUES(NULL, 'CINZA');

UPDATE CARRO
SET ID_MARCA = (SELECT IDMARCA FROM MARCA WHERE MARCA = 'FIAT')
WHERE MODELO = 'UNO';

UPDATE CARRO 
SET ID_MARCA = (SELECT IDMARCA FROM MARCA WHERE MARCA = 'HONDA')
WHERE MODELO = 'FIESTA';

UPDATE CARRO 
SET ID_MARCA = (SELECT IDMARCA FROM MARCA WHERE MARCA = 'HONDA')
WHERE MODELO = 'CIVIC';

UPDATE CARRO 
SET ID_MARCA = (SELECT IDMARCA FROM MARCA WHERE MARCA = 'MAZDA')
WHERE IDCARRO = 8;

UPDATE CARRO 
SET ID_MARCA = (SELECT IDMARCA FROM MARCA WHERE MARCA = 'MAZDA')
WHERE IDCARRO = 9;

UPDATE CARRO 
SET ID_MARCA = (SELECT IDMARCA FROM MARCA WHERE MARCA = 'MITSUBISHI')
WHERE IDCARRO = 6;

UPDATE CARRO 
SET ID_MARCA = (SELECT IDMARCA FROM MARCA WHERE MARCA = 'TOYOTA')
WHERE IDCARRO = 7;

UPDATE CARRO 
SET ID_MARCA = (SELECT IDMARCA FROM MARCA WHERE MARCA = 'NISSAN')
WHERE IDCARRO = 10;

UPDATE CARRO 
SET ID_MARCA = (SELECT IDMARCA FROM MARCA WHERE MARCA = 'VOLKSWAGEN')
WHERE IDCARRO = 5;

UPDATE CARRO 
SET ID_MARCA = (SELECT IDMARCA FROM MARCA WHERE MARCA = 'BMW')
WHERE IDCARRO = 3;

INSET INTO CARRO_COR VALUES(1, 6);
INSET INTO CARRO_COR VALUES(8, 1);
INSET INTO CARRO_COR VALUES(9, 2);
INSET INTO CARRO_COR VALUES(10, 5);
INSET INTO CARRO_COR VALUES(2, 3);
INSET INTO CARRO_COR VALUES(3, 2);
INSET INTO CARRO_COR VALUES(4, 5);
INSET INTO CARRO_COR VALUES(5, 4);
INSET INTO CARRO_COR VALUES(6, 1);
INSET INTO CARRO_COR VALUES(7, 3);

-- Teste

SELECT M.MARCA, C.MODELO, C.PLACA
FROM MARCA M
INNER JOIN CARRO C
ON ID_MARCA = IDMARCA;















